### ISSUE TITLE
Ids算法有bug

### ISSUE THREAD

**Issue by njkfei** [ihaolin/dubbo-trace#1]
counter自增和时间不相关，导致当counter自增至4096时，且正好再次请求id正好在同一毫秒，那么，会报异常。
解决方法：
如果两次请求不在同一毫秒，计算器counter重设为零。
同一毫秒内，counter使用自增值。

```
        if (currentMillisecond == lastMillisecond) {
            // 只有同一毫秒内，才使用小序号
            int count = counter.incrementAndGet();
            //如果计数器达到上限
            if (count >= MAX_COUNTER) {
                //同一毫秒内，直接抛异常，由调用方处理
                throw new RuntimeException("too much requests cause counter overflow");
            }
        }else{
            // 计数器重设为0，只有同一毫秒内，才使用小序号
            this.counter.set(0);
        }
```

**Comment by ihaolin** [comment]
这个是从其他项目copy来，不过没看出与原来的Ids太大区别，只是原来的Ids多判断了一次`count >= MAX_COUNTER`，你这个要清晰简洁些，另外本机死循环测试，也是很少会有overflow。

**Comment by njkfei** [comment]
```
ab -n 100000 - c 100 localhost:xxxx/yyyy 
```
很容易复现。

你这个组件是从url开始埋点的，然后传递到consumer,provider.
我明天试试，从(url+consumerA)->(providerA+comsumerB) ->providerB.
看能否成功。
能成功，才说明有生产环境的意义。
因为，一般的系统是这样的，站点层->业务逻辑层->原子服务层。
这里面，业务逻辑层即是服务提供者，又是服务消费者。明天试试中间层能否将trace传递到原子服务层。

**Comment by ihaolin** [comment]
+ 确实有所复现，大致是由于**多余的count变量声明**和**count >= MAX_COUNTER**造成，极短时间内有可能就溢出了。

+ 这个只要是dubbo服务的架构，`(url+consumerA)->(providerA+comsumerB) ->providerB->...`这样就可以无限传递数据，但要保证是单线程模型，多线程还需要借助其他方式，生产上也是这么的。

**Comment by njkfei** [comment]
已确认，多级服务调用可以正常追踪。谢谢您。
请问单线程和多线程的具体场景是什么呢？这点我不明白。

**Comment by ihaolin** [comment]
这里简单说，就是**Provider端接收到数据的线程**和**该Provider发起后续服务调用时的线程**必须一致，否则**ThreadLocal**就会失效，若还想跟踪本次调用期间的其他过程，也要保证这点。

**Comment by ExtremeYu** [comment]
@njkfei 你好，加入了这两个filter后，性能有衰减吗？

**Comment by shenzhuan** [comment]
这个怎么整合的  我在自己的项目用的时候没有数据

**Comment by njkfei** [comment]
@ExtremeYu 最近准备上这个filter,预计7月份开搞,到时候我做下性能测试.
