### ISSUE TITLE
项目缺类

### ISSUE THREAD

**Issue by ExtremeYu** [ihaolin/dubbo-trace#3]
![qq 20170526165133](https://cloud.githubusercontent.com/assets/16620268/26487827/a3f1e7ba-4233-11e7-9d0f-2cfbc0750eeb.png)

**Comment by ihaolin** [comment]
这个是自动生成的，试试本地安装下`mvn clean install -DskipTests`

**Comment by ExtremeYu** [comment]
Caused by: java.lang.Error: Unresolved compilation problem:

**Comment by ExtremeYu** [comment]
不行，编译不通过！

**Comment by ihaolin** [comment]
<img width="805" alt="dubbo-trace" src="https://cloud.githubusercontent.com/assets/8662695/26517276/f5d69d8e-42c7-11e7-8d68-ff59a4794dab.png">
<img width="605" alt="dubbo-trace2" src="https://cloud.githubusercontent.com/assets/8662695/26517299/29a6c742-42c8-11e7-86b9-9926f6cc032c.png">

**Comment by ExtremeYu** [comment]
这个autovalue只支持idea吗？？？？？？？？而且代码里也没有这样写的规范啊、、、、、普通群众很受伤啊/(ㄒoㄒ)/~~
